import type { Metadata } from "next";
import ConditionalSidebar from "@/components/ConditionalSidebar";
import LogoutButton from "@/components/LogoutButton";
import { AppProviders } from './providers';
import "./globals.css";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="flex w-full h-screen overflow-hidden">
        <AppProviders>
          <ConditionalSidebar /> 
          <main className="flex-1 h-screen overflow-y-auto p-6 bg-gray-900">\
              {/* 로그아웃 버튼 */}
              <div className="absolute top-4 right-6 z-50">
              <LogoutButton />
            </div>
            {children}
          </main>
        </AppProviders>
      </body>
    </html>
  );
}